connection_type: ethernet

# Ethernet connection parameters
ethernet:
  local_machine_IP: 192.168.0.42
  local_robot_IP: 192.168.0.5
  subnet_mask: 255.255.255.0
  local_cmd_port: 25000
  local_broadcast_port: 25025

