controller_list:
  - name: jaco_arm_driver
    action_ns: follow_joint_trajectory/manipulator
    type: FollowJointTrajectory
    default: true
    joints: 
      - jaco_joint_1
      - jaco_joint_2
      - jaco_joint_3
      - jaco_joint_4
      - jaco_joint_5
      - jaco_joint_6
