controller_list:
  - name: jaco_21_driver
    action_ns: follow_joint_trajectory/manipulator
    type: FollowJointTrajectory
    default: true
    joints: 
      - jaco_right_joint_1
      - jaco_right_joint_2
      - jaco_right_joint_3
      - jaco_right_joint_4
      - jaco_right_joint_5
      - jaco_right_joint_6
