sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /camera/depth_registered/points
    max_range: 0.9
    point_subsample: 1
    padding_offset: 0.0
    padding_scale: 0.8
    max_update_rate: 2.0
    filtered_cloud_topic: filtered_cloud
